### ISSUE TITLE
New User Key-Value service

### ISSUE THREAD

**Issue by shirey** [x-atlas-consortia/user-key-value-api#1]
The portal UI needs to store/read simple user specific information. To support this a new RESTful service as described in the [User Key/Value store API document](https://docs.google.com/document/d/1FoT9E3nmP0uYU4M0c5Ck1DJRe4b-pR7zto19u5h-RtE/edit?usp=sharing).  For this first, initial version of this service implement only the following endpoints (others will be done under a different card):
  - GET /user/keys/\<key\>
  - PUT/POST /user/keys/\<key\>
  - GET /status

Discussion/Design Decision needed: Likely we will back this with the existing MySQL cluster.  To that end, we should discuss if the userid, key (attribute name) and value are three separate columns or if key and value are two columns as described below.

Add the Globus Identity ID (as show in graphic below) followed by a colon ":" to all keys coming in endpoint requests/urls to lookup/add keys in the key-value store. The user's Globus Identity ID will be retrieved form the required Auth Bearer token.  For example if `GET /user/keys/mykeyname` is called with a token for the user shown below the key as sent to the backend key-value store will be:

          `e19adbbb-73c3-43a7-b05e-0eead04f5ff8:mykeyname`

![Image](https://github.com/user-attachments/assets/6489b26b-8038-4d3c-8e12-450a97ae8bd4)

**Comment by yuanzhou** [comment]
This new API is up running on DEV at https://ukv-api.dev.hubmapconsortium.org/

@kburke here are the tweaks I mentioned:

- Add json response body to the 200 responses:
```
return jsonify({'message': "message to indicate the key/value has been saved"})
```

- Wrap the 400 and 500 error responses with json envelop:
```
return jsonify({'error': "error message detail"})
```
